spring.application.name=rugbylive

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

supabase.project-url=${SUPABASE_PROJECT_URL}
supabase.jwk-set-uri=${SUPABASE_PROJECT_URL}/auth/v1/.well-known/jwks.json

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

api-sports.base-url=${API_SPORTS_BASE_URL}
api-sports.api-key=${API_SPORTS_KEY}